"""Reward rules validator worker.

Validates normalized card payloads generated by scraper/parser workers.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List


DATA_DIR = Path(__file__).resolve().parent.parent / "data"
SCRAPED_CARDS_FILE = DATA_DIR / "cards" / "scraped_cards_raw.json"
VALIDATED_OUTPUT_FILE = DATA_DIR / "cards" / "validated_cards.json"
VALIDATION_REPORT_FILE = DATA_DIR / "history" / "reward_validation_report.json"


ALLOWED_RATE_MIN = 0.0
ALLOWED_RATE_MAX = 0.20

REQUIRED_REWARD_CATEGORIES = {
    "online_shopping",
    "dining",
    "travel",
    "groceries",
    "fuel",
    "utilities",
    "general",
}


def validate_card(card: Dict) -> Dict:
    errors: List[str] = []

    annual_fee = float(card.get("annual_fee", 0) or 0)
    if annual_fee < 0:
        errors.append("annual_fee must be >= 0")

    reward_rates = card.get("reward_rates", {}) or {}
    missing = sorted(REQUIRED_REWARD_CATEGORIES - set(reward_rates.keys()))
    if missing:
        errors.append(f"missing reward categories: {', '.join(missing)}")

    for category, rate in reward_rates.items():
        value = float(rate or 0)
        if value < ALLOWED_RATE_MIN or value > ALLOWED_RATE_MAX:
            errors.append(f"invalid reward rate for {category}: {value}")

    return {
        "valid": len(errors) == 0,
        "errors": errors,
        "card_name": card.get("card_name", "Unknown Credit Card"),
        "card": card,
    }


def run_validation(cards: List[Dict]) -> Dict:
    validated_cards: List[Dict] = []
    failed_cards: List[Dict] = []

    for card in cards:
        result = validate_card(card)
        if result["valid"]:
            validated_cards.append(card)
        else:
            failed_cards.append(
                {
                    "card_name": result["card_name"],
                    "errors": result["errors"],
                }
            )

    VALIDATED_OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    VALIDATION_REPORT_FILE.parent.mkdir(parents=True, exist_ok=True)

    with VALIDATED_OUTPUT_FILE.open("w", encoding="utf-8") as file:
        json.dump(validated_cards, file, indent=2)

    report = {
        "status": "completed",
        "worker": "reward_rules_validator",
        "validated_count": len(validated_cards),
        "failed_count": len(failed_cards),
        "failed_cards": failed_cards,
        "output_file": str(VALIDATED_OUTPUT_FILE),
    }

    with VALIDATION_REPORT_FILE.open("w", encoding="utf-8") as file:
        json.dump(report, file, indent=2)

    return report


def run_reward_validation() -> Dict:
    if not SCRAPED_CARDS_FILE.exists():
        return {
            "status": "skipped",
            "worker": "reward_rules_validator",
            "reason": f"missing scrape output: {SCRAPED_CARDS_FILE}",
        }

    with SCRAPED_CARDS_FILE.open("r", encoding="utf-8") as file:
        cards = json.load(file)

    return run_validation(cards)


class RewardRulesValidatorWorker:
    """Backward-compatible validator worker used by orchestrator."""

    def validate_reward_rule(self, reward_rule: Dict) -> Dict:
        category = reward_rule.get("category")
        rate = float(reward_rule.get("reward_rate", 0) or 0)

        errors: List[str] = []
        if category not in REQUIRED_REWARD_CATEGORIES:
            errors.append(f"unsupported category: {category}")

        if rate < ALLOWED_RATE_MIN or rate > ALLOWED_RATE_MAX:
            errors.append(f"invalid reward rate for {category}: {rate}")

        return {
            "valid": len(errors) == 0,
            "errors": errors,
            "reward_rule": reward_rule,
        }
